### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by Justsubh01** [FrancescoSaverioZuppichini/A-journey-into-Convolutional-Neural-Network-visualization-#3]
hello thanks for wonderful project, i am facing an error while visualizing an image.

`AttributeError: 'NoneType' object has no attribute 'data'`

and that error indication line below in visualisation/core/SaliencyMap.py:

`image = self.gradients.data.cpu().numpy()[0]`

it is understandable because self.gradients initialized as `None`.

 how can i fix it ?

**Comment by FrancescoSaverioZuppichini** [comment]
Hi!

Thank you for the kind feedback, would you like to share a minimum example that I can locally? It may also help if you share your PyTorch version

Thank!

Cheers,

Francesco

**Comment by Justsubh01** [comment]
Sorry for late reply!

I was using  torch=='1.9.0+cu102'

I was facing error in below code block, from your article : 'https://towardsdatascience.com/a-journey-into-convolutional-neural-network-visualization-1abc71605209'

```
from visualization.core.utils import image_net_postprocessing
model.eval()
model = model.to(device)
vis = SaliencyMap(model, device)

out, info = vis(inputs[0],  #<========================== this line causing error
          first_layer)

subplot([image_net_postprocessing(inputs[0].squeeze().cpu()), out], 
        rows_titles=['original', 'saliency map'],
        parse=tensor2img, 
        nrows=1, ncols=2)
```

Thanks for your reply,

**Comment by minjoony** [comment]
@FrancescoSaverioZuppichini 
Hello, I have a same problem with your codes.
There is no problem when I using EfficientNet-b0.
But, EfficientNet-b6 makes this error.
How can I fix it?

Thanks.

**Comment by minjoony** [comment]
> @FrancescoSaverioZuppichini Hello, I have a same problem with your codes. There is no problem when I using EfficientNet-b0. But, EfficientNet-b6 makes this error. How can I fix it?
> 
> Thanks.

Hi, I solved the problem.
I used "nn.DataParallel" when I trained the model (EfficientNet-b6).
So I need to use "model.module" to call the trained model.
Here is my code snippet.

```model = efficientnet(pretrained=True).to(device)
model.load_state_dict(torch.load(CP_PATH + SAVED_DICT + '.pth.tar')['state_dict'])
model.eval()

vis = GradCam(model.module, device)
```

Thanks.

**Comment by FrancescoSaverioZuppichini** [comment]
Super!
